name: Dockerize application

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          - name: Build and Publish API
            uses: docker/build-push-action@v2
            with:
                password: ${{ secrets.DOCKER_PASSWORD }}
                push: true
                tags: nayzbysodium/chatapp-api:${{ github.run_number }} , nayzbysodium/chatapp-api:latest
                context: ./api
          - name: Build and Publish CLIENT
            uses: docker/build-push-action@v2
            with:
                password: ${{ secrets.DOCKER_PASSWORD }}
                push: true
                tags: nayzbysodium/chatapp-client:${{ github.run_number }} , nayzbysodium/chatapp-client:latest
                context: ./client
